package interface_adapter;

import use_case.ChatService;

/**
 * ChatController manages the interaction between the user and the chat service.
 */
public class ChatController {
    private final ChatService chatService;

    /**
     * Constructs a new ChatController with the specified ChatService.
     * @param chatService the ChatService used to generate responses
     */
    public ChatController(ChatService chatService) {
        this.chatService = chatService;
    }

    /**
     * Gets the response from the chat service based on the user's prompt.
     * @param prompt the user's input prompt for the chat service
     * @return the response generated by the chat service
     */
    public String getResponse(String prompt) {
        return chatService.generateResponse(prompt);
    }
}