package use_case;

import data_access.GptApiClient;

/**
 * ChatService handles the business logic for generating chat responses.
 */
public class ChatService {
    private final GptApiClient gptApiClient;

    /**
     * Constructs a new ChatService with the specified GptApiClient.
     *
     * @param gptApiClient the GptApiClient used to interact with the GPT-4 API
     */
    public ChatService(GptApiClient gptApiClient) {
        this.gptApiClient = gptApiClient;
    }

    /**
     * Generates a response from the GPT-3.5 API based on the user's input.
     *
     * @param userInput the user's input for the chat service
     * @return the response generated by the GPT-3.5 API
     */
    public String generateResponse(String userInput) {
        return gptApiClient.getChatCompletion(userInput);
    }
}